#ifndef CODEC_CONTEXT_H
#define CODEC_CONTEXT_H
#include "../utils.h"
#include <libavcodec/avcodec.h>
#include <node_api.h>

static void freeContext(napi_env env, void *finalize_data,
                        void *finalize_hint) {
  avcodec_free_context((AVCodecContext **)&finalize_data);
}

WRAP(createAVCodecContext, AVCodecContext *, freeContext,
     PROP_CONST(codecType, NUMBER(native->codec_type)), PROP_CONST(codec, NULL),
     PROP_CONST(codecId, NUMBER(native->codec_id)),
     PROP_CONST(codecTag, NUMBER(native->codec_tag)),
     PROP_CONST(privData, NULL), PROP_CONST(bitRate, NUMBER(native->bit_rate)),
     PROP_CONST(flags, NUMBER(native->flags)),
     PROP_CONST(flags2, NUMBER(native->flags2)), PROP_CONST(timeBase, NULL),
     PROP_CONST(pktTimebase, NULL), PROP_CONST(framerate, NULL),
     PROP_CONST(delay, NUMBER(native->delay)),
     PROP_CONST(width, NUMBER(native->width)),
     PROP_CONST(height, NUMBER(native->height)),
     PROP_CONST(codedWidth, NUMBER(native->coded_width)),
     PROP_CONST(codedHeight, NUMBER(native->coded_height)),
     PROP_CONST(sampleAspectRatio, NULL),
     PROP_CONST(pixFmt, NUMBER(native->pix_fmt)),
     PROP_CONST(swPixFmt, NUMBER(native->sw_pix_fmt)),
     PROP_CONST(colorPrimaries, NUMBER(native->color_primaries)),
     PROP_CONST(colorTrc, NUMBER(native->color_trc)),
     PROP_CONST(colorspace, NUMBER(native->colorspace)),
     PROP_CONST(colorRange, NUMBER(native->color_range)),
     PROP_CONST(chromaSampleLocation, NUMBER(native->chroma_sample_location)),
     PROP_CONST(fieldOrder, NUMBER(native->field_order)),
     PROP_CONST(refs, NUMBER(native->refs)),
     PROP_CONST(hasBFrames, NUMBER(native->has_b_frames)),
     PROP_CONST(sliceFlags, NUMBER(native->slice_flags)),
     PROP_CONST(drawHorizBand, NULL), PROP_CONST(getFormat, NULL),
     PROP_CONST(maxBFrames, NUMBER(native->max_b_frames)),
     PROP_CONST(bQuantFactor, NUMBER(native->b_quant_factor)),
     PROP_CONST(bQuantOffset, NUMBER(native->b_quant_offset)),
     PROP_CONST(iQuantFactor, NUMBER(native->i_quant_factor)),
     PROP_CONST(iQuantOffset, NUMBER(native->i_quant_offset)),
     PROP_CONST(lumiMasking, NUMBER(native->lumi_masking)),
     PROP_CONST(temporalCplxMasking, NUMBER(native->temporal_cplx_masking)),
     PROP_CONST(spatialCplxMasking, NUMBER(native->spatial_cplx_masking)),
     PROP_CONST(pMasking, NUMBER(native->p_masking)),
     PROP_CONST(dark_masking, NUMBER(native->dark_masking)),
     PROP_CONST(nsseWeight, NUMBER(native->nsse_weight)),
     PROP_CONST(meCmp, NUMBER(native->me_cmp)),
     PROP_CONST(meSubCmp, NUMBER(native->me_sub_cmp)),
     PROP_CONST(mbCmp, NUMBER(native->mb_cmp)),
     PROP_CONST(ildctCmp, NUMBER(native->ildct_cmp)),
     PROP_CONST(diaSize, NUMBER(native->dia_size)),
     PROP_CONST(lastPredictorCount, NUMBER(native->last_predictor_count)),
     PROP_CONST(mePreCmp, NUMBER(native->me_pre_cmp)),
     PROP_CONST(preDiaSize, NUMBER(native->pre_dia_size)),
     PROP_CONST(meSubpelQuality, NUMBER(native->me_subpel_quality)),
     PROP_CONST(meRange, NUMBER(native->me_range)),
     PROP_CONST(mbDecision, NUMBER(native->mb_decision)),
     PROP_CONST(intraMatrix, NULL), PROP_CONST(interMatrix, NULL),
     PROP_CONST(chromaIntraMatrix, NULL),
     PROP_CONST(intraDcPrecision, NUMBER(native->intra_dc_precision)),
     PROP_CONST(mbLmin, NUMBER(native->mb_lmin)),
     PROP_CONST(mbLmax, NUMBER(native->mb_lmax)),
     PROP_CONST(bidirRefine, NUMBER(native->bidir_refine)),
     PROP_CONST(keyintMin, NUMBER(native->keyint_min)),
     PROP_CONST(gopSize, NUMBER(native->gop_size)),
     PROP_CONST(mv0Threshold, NUMBER(native->mv0_threshold)),
     PROP_CONST(slices, NUMBER(native->slices)),
     PROP_CONST(sampleRate, NUMBER(native->sample_rate)),
     PROP_CONST(sampleFmt, NUMBER(native->sample_fmt)),
     PROP_CONST(chLayout, NULL),
     PROP_CONST(frameSize, NUMBER(native->frame_size)),
     PROP_CONST(blockAlign, NUMBER(native->block_align)),
     PROP_CONST(cutoff, NUMBER(native->cutoff)),
     PROP_CONST(audioServiceType, NUMBER(native->audio_service_type)),
     PROP_CONST(requestSampleFmt, NUMBER(native->request_sample_fmt)),
     PROP_CONST(initialPadding, NUMBER(native->initial_padding)),
     PROP_CONST(seekPreroll, NUMBER(native->seek_preroll)),
     PROP_CONST(getBuffer2, NULL),
     PROP_CONST(bitRateTolerance, NUMBER(native->bit_rate_tolerance)),
     PROP_CONST(globalQuality, NUMBER(native->global_quality)),
     PROP_CONST(compressionLevel, NUMBER(native->compression_level)),
     PROP_CONST(qcompress, NUMBER(native->qcompress)),
     PROP_CONST(qblur, NUMBER(native->qblur)),
     PROP_CONST(qmin, NUMBER(native->qmin)),
     PROP_CONST(qmax, NUMBER(native->qmax)),
     PROP_CONST(maxQdiff, NUMBER(native->max_qdiff)),
     PROP_CONST(rcBufferSize, NUMBER(native->rc_buffer_size)),
     PROP_CONST(rcOverrideCount, NUMBER(native->rc_override_count)),
     PROP_CONST(rcOverride, NULL),
     PROP_CONST(rcMaxRate, NUMBER(native->rc_max_rate)),
     PROP_CONST(rcMinRate, NUMBER(native->rc_min_rate)),
     PROP_CONST(rcMaxAvailableVbvUse, NUMBER(native->rc_max_available_vbv_use)),
     PROP_CONST(rcMinVbvOverflowUse, NUMBER(native->rc_min_vbv_overflow_use)),
     PROP_CONST(rcInitialBufferOccupancy,
                NUMBER(native->rc_initial_buffer_occupancy)),
     PROP_CONST(trellis, NUMBER(native->trellis)),
     PROP_CONST(statsOut, STRING(native->stats_out)),
     PROP_CONST(statsIn, STRING(native->stats_in)),
     PROP_CONST(workaroundBugs, NUMBER(native->workaround_bugs)),
     PROP_CONST(strictStdCompliance, NUMBER(native->strict_std_compliance)),
     PROP_CONST(errorConcealment, NUMBER(native->error_concealment)),
     PROP_CONST(debug, NUMBER(native->debug)),
     PROP_CONST(errRecognition, NUMBER(native->err_recognition)),
     PROP_CONST(hwaccel, NULL), PROP_CONST(hwaccelContext, NULL),
     PROP_CONST(hwFramesCtx, NULL), PROP_CONST(hwDeviceCtx, NULL),
     PROP_CONST(hwaccelFlags, NUMBER(native->hwaccel_flags)),
     PROP_CONST(extraHwFrames, NUMBER(native->extra_hw_frames)),
     PROP_CONST(error, NULL), PROP_CONST(dctAlgo, NUMBER(native->dct_algo)),
     PROP_CONST(idctAlgo, NUMBER(native->idct_algo)),
     PROP_CONST(bitsPerCodedSample, NUMBER(native->bits_per_coded_sample)),
     PROP_CONST(bitsPerRawSample, NUMBER(native->bits_per_raw_sample)),
     PROP_CONST(threadCount, NUMBER(native->thread_count)),
     PROP_CONST(threadType, NUMBER(native->thread_type)),
     PROP_CONST(activeThreadType, NUMBER(native->active_thread_type)),
     PROP_CONST(execute, NULL), PROP_CONST(execute2, NULL),
     PROP_CONST(profile, NUMBER(native->profile)),
     PROP_CONST(level, NUMBER(native->level)),
     PROP_CONST(skipLoopFilter, NUMBER(native->skip_loop_filter)),
     PROP_CONST(skipIdct, NUMBER(native->skip_idct)),
     PROP_CONST(skipFrame, NUMBER(native->skip_frame)),
     PROP_CONST(skipAlpha, NUMBER(native->skip_alpha)),
     PROP_CONST(skipTop, NUMBER(native->skip_top)),
     PROP_CONST(skipBottom, NUMBER(native->skip_bottom)),
     PROP_CONST(lowres, NUMBER(native->lowres)),
     PROP_CONST(codecDescriptor, NULL),
     PROP_CONST(subCharenc, STRING(native->sub_charenc)),
     PROP_CONST(subCharencMode, NUMBER(native->sub_charenc_mode)),
     PROP_CONST(subtitleHeader, NULL), PROP_CONST(dumpSeparator, NULL),
     PROP_CONST(codecWhitelist, STRING(native->codec_whitelist)),
     PROP_CONST(codedSideData, NULL),
     PROP_CONST(exportSideData, NUMBER(native->export_side_data)),
     PROP_CONST(maxPixels, BIGINT64(native->max_pixels)),
     PROP_CONST(applyCropping, NUMBER(native->apply_cropping)),
     PROP_CONST(discardDamagedPercentage,
                NUMBER(native->discard_damaged_percentage)),
     PROP_CONST(maxSamples, BIGINT64(native->max_samples)),
     PROP_CONST(getEncodeBuffer, NULL),
     PROP_CONST(frameNum, BIGINT64(native->frame_num)),
     PROP_CONST(sideDataPreferPacket, NULL), PROP_CONST(decodedSideData, NULL),
     PROP_CONST(alphaMode, NUMBER(native->alpha_mode)));
#endif