#ifndef CODEC_CONTEXT_H
#define CODEC_CONTEXT_H
#include "../utils.h"
#include "codec.h"
#include <libavcodec/avcodec.h>

static void finalizeContext(napi_env env, void *finalize_data,
                            void *finalize_hint) {
  avcodec_free_context((AVCodecContext **)&finalize_data);
}

WRAP(createAVCodecContext, AVCodecContext, finalizeContext,
     PROP_CONST(codecType, NUMBER(native->codec_type)),
     PROP_CONST(codec, createAVCodec(env, native->codec)),
     PROP_CONST(codecId, NUMBER(native->codec_id)),
     PROP_GETSET(codecTag, codec_tag, int),
     PROP_CONST(privData, EXTERNAL(native->priv_data)),
     PROP_GETSET(bitRate, bit_rate, int64_t), PROP_GETSET(flags, flags, int),
     PROP_GETSET(flags2, flags2, int),
     PROP_GETSET(timeBase, time_base, AVRational),
     PROP_GETSET(pktTimebase, pkt_timebase, AVRational),
     PROP_GETSET(framerate, framerate, AVRational), PROP_GET(delay, delay, int),
     PROP_GETSET(width, width, int), PROP_GETSET(height, height, int),
     PROP_GETSET(codedWidth, coded_width, int),
     PROP_GETSET(codedHeight, coded_height, int),
     PROP_GETSET(sampleAspectRatio, sample_aspect_ratio, AVRational),
     PROP_GETSET(pixFmt, pix_fmt, int), PROP_GET(swPixFmt, sw_pix_fmt, int),
     PROP_GETSET(colorPrimaries, color_primaries, int),
     PROP_GETSET(colorTrc, color_trc, int),
     PROP_GETSET(colorspace, colorspace, int),
     PROP_GETSET(colorRange, color_range, int),
     PROP_GETSET(chromaSampleLocation, chroma_sample_location, int),
     PROP_GETSET(fieldOrder, field_order, int), PROP_GETSET(refs, refs, int),
     PROP_GET(hasBFrames, has_b_frames, int),
     PROP_GETSET(sliceFlags, slice_flags, int), PROP_CONST(drawHorizBand, NULL),
     PROP_CONST(getFormat, NULL), PROP_GETSET(maxBFrames, max_b_frames, int),
     PROP_GETSET(bQuantFactor, b_quant_factor, float),
     PROP_GETSET(bQuantOffset, b_quant_offset, float),
     PROP_GETSET(iQuantFactor, i_quant_factor, float),
     PROP_GETSET(iQuantOffset, i_quant_offset, float),
     PROP_GETSET(lumiMasking, lumi_masking, float),
     PROP_GETSET(temporalCplxMasking, temporal_cplx_masking, float),
     PROP_GETSET(spatialCplxMasking, spatial_cplx_masking, float),
     PROP_GETSET(pMasking, p_masking, float),
     PROP_GETSET(dark_masking, dark_masking, float),
     PROP_GETSET(nsseWeight, nsse_weight, int), PROP_GETSET(meCmp, me_cmp, int),
     PROP_GETSET(meSubCmp, me_sub_cmp, int), PROP_GETSET(mbCmp, mb_cmp, int),
     PROP_GETSET(ildctCmp, ildct_cmp, int), PROP_GETSET(diaSize, dia_size, int),
     PROP_GETSET(lastPredictorCount, last_predictor_count, int),
     PROP_GETSET(mePreCmp, me_pre_cmp, int),
     PROP_GETSET(preDiaSize, pre_dia_size, int),
     PROP_GETSET(meSubpelQuality, me_subpel_quality, int),
     PROP_GETSET(meRange, me_range, int),
     PROP_GETSET(mbDecision, mb_decision, int), PROP_CONST(intraMatrix, NULL),
     PROP_CONST(interMatrix, NULL), PROP_CONST(chromaIntraMatrix, NULL),
     PROP_GETSET(intraDcPrecision, intra_dc_precision, int),
     PROP_GETSET(mbLmin, mb_lmin, int), PROP_GETSET(mbLmax, mb_lmax, int),
     PROP_GETSET(bidirRefine, bidir_refine, int),
     PROP_GETSET(keyintMin, keyint_min, int),
     PROP_GETSET(gopSize, gop_size, int),
     PROP_GETSET(mv0Threshold, mv0_threshold, int),
     PROP_GETSET(slices, slices, int),
     PROP_GETSET(sampleRate, sample_rate, int),
     PROP_GETSET(sampleFmt, sample_fmt, int), PROP_CONST(chLayout, NULL),
     PROP_GET(frameSize, frame_size, int),
     PROP_GET(blockAlign, block_align, int), PROP_GETSET(cutoff, cutoff, int),
     PROP_GETSET(audioServiceType, audio_service_type, int),
     PROP_GETSET(requestSampleFmt, request_sample_fmt, int),
     PROP_GET(initialPadding, initial_padding, int),
     PROP_GET(seekPreroll, seek_preroll, int), PROP_CONST(getBuffer2, NULL),
     PROP_GETSET(bitRateTolerance, bit_rate_tolerance, int),
     PROP_GETSET(globalQuality, global_quality, int),
     PROP_GETSET(compressionLevel, compression_level, int),
     PROP_GETSET(qcompress, qcompress, float), PROP_GETSET(qblur, qblur, float),
     PROP_GETSET(qmin, qmin, int), PROP_GETSET(qmax, qmax, int),
     PROP_GETSET(maxQdiff, max_qdiff, int),
     PROP_GETSET(rcBufferSize, rc_buffer_size, int),
     PROP_CONST(rcOverrideCount, NULL), PROP_CONST(rcOverride, NULL),
     PROP_GETSET(rcMaxRate, rc_max_rate, int64_t),
     PROP_GETSET(rcMinRate, rc_min_rate, int64_t),
     PROP_GETSET(rcMaxAvailableVbvUse, rc_max_available_vbv_use, float),
     PROP_GETSET(rcMinVbvOverflowUse, rc_min_vbv_overflow_use, float),
     PROP_GETSET(rcInitialBufferOccupancy, rc_initial_buffer_occupancy, int),
     PROP_GETSET(trellis, trellis, int), PROP_GET(statsOut, stats_out, string),
     PROP_GETSET(statsIn, stats_in, string),
     PROP_GETSET(workaroundBugs, workaround_bugs, int),
     PROP_GETSET(strictStdCompliance, strict_std_compliance, int),
     PROP_GETSET(errorConcealment, error_concealment, int),
     PROP_GETSET(debug, debug, int),
     PROP_GETSET(errRecognition, err_recognition, int),
     PROP_CONST(hwaccel, NULL), PROP_CONST(hwaccelContext, NULL),
     PROP_CONST(hwFramesCtx, NULL), PROP_CONST(hwDeviceCtx, NULL),
     PROP_GETSET(hwaccelFlags, hwaccel_flags, int),
     PROP_GETSET(extraHwFrames, extra_hw_frames, int), PROP_CONST(error, NULL),
     PROP_GETSET(dctAlgo, dct_algo, int), PROP_GETSET(idctAlgo, idct_algo, int),
     PROP_GETSET(bitsPerCodedSample, bits_per_coded_sample, int),
     PROP_GETSET(bitsPerRawSample, bits_per_raw_sample, int),
     PROP_GETSET(threadCount, thread_count, int),
     PROP_GETSET(threadType, thread_type, int),
     PROP_GET(activeThreadType, active_thread_type, int),
     PROP_CONST(execute, NULL), PROP_CONST(execute2, NULL),
     PROP_GETSET(profile, profile, int), PROP_GETSET(level, level, int),
     PROP_GETSET(skipLoopFilter, skip_loop_filter, int),
     PROP_GETSET(skipIdct, skip_idct, int),
     PROP_GETSET(skipFrame, skip_frame, int),
     PROP_GETSET(skipAlpha, skip_alpha, int),
     PROP_GETSET(skipTop, skip_top, int),
     PROP_GETSET(skipBottom, skip_bottom, int),
     PROP_GETSET(lowres, lowres, int), PROP_CONST(codecDescriptor, NULL),
     PROP_GETSET(subCharenc, sub_charenc, string),
     PROP_GET(subCharencMode, sub_charenc_mode, int),
     PROP_CONST(subtitleHeader, NULL), PROP_CONST(dumpSeparator, NULL),
     PROP_GETSET(codecWhitelist, codec_whitelist, string),
     PROP_CONST(codedSideData, NULL),
     PROP_GETSET(exportSideData, export_side_data, int),
     PROP_GETSET(maxPixels, max_pixels, int64_t),
     PROP_GETSET(applyCropping, apply_cropping, int),
     PROP_GETSET(discardDamagedPercentage, discard_damaged_percentage, int),
     PROP_GETSET(maxSamples, max_samples, int64_t),
     PROP_CONST(getEncodeBuffer, NULL), PROP_GET(frameNum, frame_num, int64_t),
     PROP_CONST(sideDataPreferPacket, NULL), PROP_CONST(decodedSideData, NULL),
     PROP_GETSET(alphaMode, alpha_mode, int));
#endif